version: "3"
services:
  redis:
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - PORT=8082
    ports:
      - "8082:8082"
